pool:
  name: Hosted Ubuntu 1604
  demands: maven

steps:
- task: Maven@1
  displayName: 'Maven $(mavenPOMFile)'
  inputs:
    mavenPomFile: app/pom.xml
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/*.war
     **/*jar-with-dependencies.jar
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: drop'
